services:
  postgres:
    container_name: postgres
    image: postgres:16.3-alpine3.19
    networks:
      - net
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart:
      unless-stopped

  back:
    container_name: back
    build:
      dockerfile: ./back/Dockerfile
    networks:
      - net
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    depends_on:
      - postgres

networks:
  net:

volumes:
  postgres_data:
